### ISSUE TITLE
Create a scratch org

### ISSUE THREAD

**Issue by bestWenshu** [Miguel-Matos/EERE_Portal#8]
1. Enable dev hub

2. Create project

3. Creatch scratch org
sf org create scratch -f config/project-scratch-def.json -a MyScratchOrg -v DevHubAlias -d

4. Going to our new scratch org using command:
sf org open -o MyScratchOrg

5. Source convert
sf force source convert -d metadataFolder

6. Deploy
sf force mdapi deploy -d metadataFolder -u MyScratchOrg

**Comment by Miguel-Matos** [comment]
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_create.htm

**Comment by Miguel-Matos** [comment]
What was done

sf org create scratch -f config/project-scratch-def.json -a eereOrg -v eereScratch -d
sf org open -o eereOrg
